### PR TITLE
cleaned up and formatting 2020-11-24

### PR DESCRIPTION
**Pull request by netzgestaltung**
should be no code changes

### CODE REVIEW

**Review by aurovrata — COMMENTED** [review]
can you comment your changes as it is difficult to see what you have done

**Comment by netzgestaltung** [comment]
i only formatted the code, spaces in brackets, indenting and readability stuff. so i changed all lines but the logic and markup stayed untouched. Its just a preperation for further easier development.

**Comment by aurovrata** [comment]
ok, but doesn't warrant a PR as yet.

If you are interested in contributing to the plugin (which you are most welcome to), I would suggest that we coordinate our efforts.

I have started a [Roadmap](https://github.com/aurovrata/Post-My-CF7-Form/wiki/Roadmap) wiki page listing some of the functionality to aim for in a re-write of the code.

**Comment by netzgestaltung** [comment]
Hi,

i now tested with menu dropdown fields and the same happens. so if i want to map more then 1 taxonomy it all breaks.

To the roadmap i can add JCF as custom field plugin, it uses the default meta fields from WP. 
I don't know if i can access ACF fields with `get_post_meta()` or `get_post_custom()`. 

But if so, i would use the default WP way - using all meta fields starting with `_`.

**Comment by netzgestaltung** [comment]
The author field also disapears after map publishing and also does not get saved with the form submission. Does it expect an ID?

**Comment by aurovrata** [comment]
>The author field also disapears after map publishing

I noticed that too, and realised this is an issue with the javascript.

> and also does not get saved with the form submission. Does it expect an ID?

yes

>To the roadmap i can add JCF as custom field plugin,

what is JCF?

**Comment by aurovrata** [comment]
I have created a new branch 5.0 on which I will be merging your changes and recoding parts of the plugin to improve the admin interface and performance.

thank you for your contribution, I will be adding you as a contributor on the plugin page :smiley:

**Pull request merged**
